# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test-meetic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7.0'
  pod 'SDWebImage', '~> 4.0'

  # Pods for test-meetic

  target 'test-meeticTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
